import { ReactElement } from 'react';

import { Layout } from 'components/layout/layout';
import Head from 'next/head';

interface PageProps {
  children: ReactElement;
}

export const Page = (props: PageProps) => {
  return (
    <>
      <Head>
        <title>Gym</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />

        <meta charSet='utf-8' />
        <meta httpEquiv='X-UA-Compatible' content='IE=edge' />
        <meta
          name='viewport'
          content='width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no'
        />
        <meta name='description' content='Description' />
        <meta name='keywords' content='Keywords' />
        <title>Next.js PWA Example</title>

        <link rel='manifest' href='/manifest.json' />
        <link href='/ios/16.png' rel='icon' type='image/png' sizes='16x16' />
        <link href='/ios/32.png' rel='icon' type='image/png' sizes='32x32' />
        <link rel='apple-touch-icon' href='/apple-icon.png'></link>
        <meta name='theme-color' content='#4B74F7' />
      </Head>
      <Layout>{props.children}</Layout>
    </>
  );
};
