import { ReactElement } from 'react';

import { Layout } from 'components/layout/layout';
import Head from 'next/head';

interface PageProps {
  children: ReactElement;
}

export const Page = (props: PageProps) => {
  return (
    <>
      <Head>
        <title>Gym</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>{props.children}</Layout>
    </>
  );
};
